"""
Django settings for mnemotopy project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from kombu import Queue, Exchange

ugettext = lambda s: s  # dummy ugettext function, as django's docs say


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, 'mnemotopy'))
BASE_PATH = os.path.normpath(os.path.join(PROJECT_PATH, os.pardir))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!fa1dui8$1j$q90m!dst351oc)$4vz-w-x8kt5=+i49tp&umg+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'mnemotopy.apps.MnemotopyConfig',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'django_extensions',
    'pure_pagination',
    'djcelery',
    'sorl.thumbnail',
    'django_user_agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'mnemotopy.middleware.locale.CustomLocaleMiddleware',
]

ROOT_URLCONF = 'mnemotopy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]


WSGI_APPLICATION = 'mnemotopy.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

TIME_ZONE = 'UTC'
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en', ugettext('English')),
    ('fr', ugettext('French')),
)

ALLOWED_LANGUAGES = (
    ('en', ugettext('English')),
    ('fr', ugettext('French')),
)

USE_I18N = True
USE_L10N = True

MEDIA_URL = '/media/'
LOCAL_MEDIA_URL = MEDIA_URL
MEDIA_ROOT = os.path.join(BASE_PATH, '..', '..', 'media')
MEDIA_SECURE_URL = MEDIA_URL

STATIC_ROOT = os.path.join(BASE_PATH, '..', '..', 'static')
STATIC_URL = '/static/'
STATIC_SECURE_URL = STATIC_URL

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATICFILES_DIRS = (
    os.path.join(PROJECT_PATH, '..', 'static'),
)

LOGIN_URL = '/login/'


FORBIDDEN_SLUGS = (
    'login',
    'logout',
    'search',
    'admin',
    'i18n',
    'tags',
    'projects',
    'categories',
)

MODELTRANSLATION_TRANSLATION_FILES = (
    'mnemotopy.models.translation',
)

LANGUAGE_COOKIE_NAME = 'mp_lang'


MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

LOGIN_REDIRECT_URL = '/'


BROKER_URL = "amqp://mnemotopy:mnemotopy@localhost:5672/mnemotopy"

CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json', 'application/json', 'pickle']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.Databasecheduler'

CELERY_QUEUES = (
    Queue('media', Exchange('media'), routing_key='media'),
)
CELERY_ROUTES = {
    'mnemotopy_media.tasks.upload_to_vimeo': {
        'queue': 'media'
    },
    'mnemotopy_media.tasks.edit_vimeo_information': {
        'queue': 'media'
    },
    'mnemotopy_media.tasks.upload_compressed_image': {
        'queue': 'media'
    }
}

LOCALE_PATHS = [os.path.join(BASE_PATH, 'locale')]
