# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import mnemotopy.models.media
import separatedvaluesfield.models
import sluggable.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'mnemotopy_category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ascii name')),
                ('slug', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'cities_city',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Audio')])),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('realized_at', models.DateTimeField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('position', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mnemotopy.models.media.get_image_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=mnemotopy.models.media.get_video_path)),
                ('audio', models.FileField(blank=True, null=True, upload_to=mnemotopy.models.media.get_audio_path)),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to=mnemotopy.models.media.get_image_path)),
                ('languages', separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemotopy.City')),
            ],
            options={
                'abstract': False,
                'db_table': 'mnemotopy_project_media',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', sluggable.fields.SluggableField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('subtitle', models.CharField(max_length=255, null=True)),
                ('subtitle_en', models.CharField(max_length=255, null=True)),
                ('subtitle_fr', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True, verbose_name='Beginning of this project')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='Ending of this project')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='mnemotopy.Category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemotopy.City')),
            ],
            options={
                'db_table': 'mnemotopy_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='URL')),
                ('redirect', models.BooleanField(default=False, verbose_name='Redirection')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'mnemotopy_tag',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='mnemotopy.Tag'),
        ),
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mnemotopy.Project'),
        ),
    ]
