# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnemotopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(to='mnemotopy.Tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='mnemotopy.Project'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
